[formatter.elm-format]
command = "elm-format"
options = ["--yes"]
includes = ["elm-app/src/**/*.elm"]

[formatter.fourmolu]
command = "fourmolu"
options = ["--mode", "inplace"]
includes = ["statics/**/*.hs"]
